#!/usr/bin/env python3
"""Session 25 — Complete Candidate Harvest.
Integrates all discovered creator profiles across Volleyball, Beach Volleyball,
Fitness / Bodybuilding, and Modeling / Swimwear / Bikini fashion.
"""

SESSION25_CANDIDATES = [
    # --- Fitness & Bodybuilding Creators ---
    {"qid": "Q125814190", "name": "Sara Saffari", "dob": "2001-02-27", "occ": "fitness model", "ig": "sarasaffari__", "tt": "sarrrrrr68", "notes": "Fitness creator and athlete."},
    {"qid": "Q116211359", "name": "Odett Bernáth", "dob": "2002-09-11", "occ": "fitness model", "ig": "odettbernath", "tt": "odettbernath", "notes": "IFBB bikini competitor and fitness creator."},
    {"qid": "Q115475108", "name": "Wiktoria Ryczko", "dob": "1998-03-12", "occ": "fitness model", "ig": "wiktoriaryczko", "tt": "wiktoriaryczkoo", "notes": "Fitness model and digital athlete."},
    {"qid": "Q108282399", "name": "Sara Sarti", "dob": "1997-01-01", "occ": "fitness model", "ig": "sarinasarti", "tt": "sarinasarti", "notes": "Bikini fitness athlete and trainer."},
    {"qid": "Q13562986", "name": "Lauren Drain", "dob": "1985-12-31", "occ": "fitness model", "ig": "laurendrainfit", "tt": "laurendrainfit", "wiki": "https://en.wikipedia.org/wiki/Lauren_Drain", "notes": "IFBB Pro bikini competitor and fitness author."},
    {"qid": "Q19566049", "name": "Dana Brooke", "dob": "1988-11-29", "occ": "fitness model", "ig": "ashasebera_danabrooke", "tt": "ashasebera_danabrooke", "wiki": "https://en.wikipedia.org/wiki/Dana_Brooke", "notes": "IFBB fitness athlete and professional wrestler."},
    {"qid": "Q112576779", "name": "Abby Berner", "dob": "2001-07-09", "occ": "fitness model", "ig": "abbyberner", "tt": "abbyberner", "notes": "Fitness model and digital creator."},

    # --- Swimwear & Fashion Models ---
    {"qid": "Q117051327", "name": "Desiré Inglander", "dob": "2001-05-02", "occ": "fashion model", "ig": "desireinglander", "tt": "desiresinglander", "notes": "Top fashion and swimwear model."},
    {"qid": "Q17305993", "name": "Imaan Hammam", "dob": "1996-10-05", "occ": "fashion model", "ig": "imaanhammam", "tt": "imaanhammam", "wiki": "https://en.wikipedia.org/wiki/Imaan_Hammam", "notes": "Top international fashion and swimwear runway model."},
    {"qid": "Q116524740", "name": "Blanka Stajkow", "dob": "1999-05-23", "occ": "fashion model", "ig": "blikeblanka", "tt": "blikeblanka", "wiki": "https://en.wikipedia.org/wiki/Blanka_Stajkow", "notes": "Fashion model and music artist."},
    {"qid": "Q116672123", "name": "Anna Alimani", "dob": "1997-10-04", "occ": "fashion model", "ig": "anna_alimani", "tt": "annaalimani", "notes": "Fashion and swimwear model."},
    {"qid": "Q136866201", "name": "Phia Quantius", "dob": "1998-01-01", "occ": "fashion model", "ig": "phia_quantius", "tt": "phia_quantius", "notes": "Fashion model and creative author."},
    {"qid": "Q138460363", "name": "Yara Elsokkary", "dob": "1998-01-06", "occ": "fashion model", "ig": "yaraelsokkary", "tt": "yaraelsokkaryy", "notes": "Fashion and commercial model."},
    {"qid": "Q64783713", "name": "Airi Furuta", "dob": "2002-06-30", "occ": "fashion model", "ig": "airi_furuta", "tt": "airifuruta", "notes": "Fashion model and digital personality."},
    {"qid": "Q64783055", "name": "Noa Tsurushima", "dob": "2001-05-24", "occ": "fashion model", "ig": "felonyrose__n", "tt": "noatsurushima_official", "wiki": "https://en.wikipedia.org/wiki/Noa_Tsurushima", "notes": "Fashion model and actress."},
    {"qid": "Q64783404", "name": "Himari Ichinose", "dob": "2004-12-15", "occ": "fashion model", "ig": "lespros_himari", "tt": "lespros_himari", "notes": "Fashion model and digital creator."},
    {"qid": "Q63131441", "name": "Yua Tsutsui", "dob": "2004-01-18", "occ": "fashion model", "ig": "yuatsutsui_0118", "tt": "yuatyyy0118", "notes": "Fashion model and magazine contributor."},
    {"qid": "Q124256592", "name": "Maya Keyy", "dob": "2002-07-29", "occ": "fashion model", "ig": "maya.keyy", "tt": "mayakeyyspam", "notes": "Fashion model and lifestyle creator."},
    {"qid": "Q124044689", "name": "Konon Notoya", "dob": "2003-02-12", "occ": "fashion model", "ig": "konon_0212", "tt": "konon_0212", "notes": "Fashion model and media creator."},
    {"qid": "Q124167932", "name": "Miko Nakazawa", "dob": "2002-07-26", "occ": "fashion model", "ig": "miko_nakazawa", "tt": "miko_nakazawa", "notes": "Fashion model and digital creator."},
    {"qid": "Q123694020", "name": "Ayano Nishi", "dob": "2002-08-15", "occ": "fashion model", "ig": "achan___15", "tt": "ayapo_0815", "notes": "Fashion model and content creator."},
    {"qid": "Q123489710", "name": "Miyu Nozaki", "dob": "2004-09-11", "occ": "fashion model", "ig": "miyu_911_m", "tt": "nmiyu_911_m", "notes": "Fashion model and digital personality."},
    {"qid": "Q122354418", "name": "Norika Chiba", "dob": "2005-07-13", "occ": "fashion model", "ig": "norika_girl7", "tt": "norsoyi00", "notes": "Fashion model and digital creator."},
    {"qid": "Q121355215", "name": "Natsuki Abe", "dob": "1999-10-06", "occ": "fashion model", "ig": "i.am_natsuki_", "tt": "i.am_natsuki_", "notes": "Fashion model and beauty influencer."},
    {"qid": "Q121355254", "name": "Aoi Ihara", "dob": "1997-08-15", "occ": "fashion model", "ig": "aoi186", "tt": "aoi_staff", "notes": "Fashion model and beauty digital creator."},
    {"qid": "Q36597779", "name": "Nagisa Saitō", "dob": "2003-07-06", "occ": "fashion model", "ig": "saitou_nagisa", "tt": "equal_love_nagisa", "notes": "Fashion model and actress."},
    {"qid": "Q35567812", "name": "Nana Tanikawa", "dob": "1997-01-30", "occ": "fashion model", "ig": "pechi.130", "tt": "tanikawanana", "notes": "Fashion model and digital lifestyle creator."},
    {"qid": "Q30929649", "name": "Riri Nanatsumori", "dob": "1995-06-08", "occ": "fashion model", "ig": "riri_nanatsumori", "tt": "riri_nntmr", "notes": "Fashion model and creator."},
    {"qid": "Q48751134", "name": "Haruka Koizumi", "dob": "2001-01-05", "occ": "fashion model", "ig": "haruka_koizumi_official", "tt": "haruka_koizumi_official", "notes": "Fashion model and performing artist."},
    {"qid": "Q48756912", "name": "Kana Tokue", "dob": "1998-12-13", "occ": "fashion model", "ig": "tokue_kana", "tt": "tokue_kana", "notes": "Fashion model and television talent."},
    {"qid": "Q18700421", "name": "Aya Asahina", "dob": "1993-10-06", "occ": "fashion model", "ig": "asahina_aya", "tt": "aya.asahina", "wiki": "https://en.wikipedia.org/wiki/Aya_Asahina", "notes": "Fashion model and fitness athlete."},
    {"qid": "Q17686476", "name": "Rinka Kumada", "dob": "2001-02-23", "occ": "fashion model", "ig": "rinka_kumada0223", "tt": "rinka_kumada0223", "wiki": "https://en.wikipedia.org/wiki/Rinka_Kumada", "notes": "Fashion model and actress."},
    {"qid": "Q17685954", "name": "Miyū Ikeda", "dob": "1998-10-30", "occ": "fashion model", "ig": "michopa1030", "tt": "michopaaaaa1030", "wiki": "https://en.wikipedia.org/wiki/Miy%C5%AB_Ikeda", "notes": "Fashion model and television personality."},
    {"qid": "Q11551702", "name": "Elaiza Ikeda", "dob": "1996-04-16", "occ": "fashion model", "ig": "elaiza_ikd", "tt": "elaizaofficial_", "wiki": "https://en.wikipedia.org/wiki/Elaiza_Ikeda", "notes": "Fashion model, film director, and actress."},
    {"qid": "Q11531435", "name": "Sayuri Matsumura", "dob": "1992-08-27", "occ": "fashion model", "ig": "matsumura_sayuri_official", "tt": "sayuringo_officialtiktok", "wiki": "https://en.wikipedia.org/wiki/Sayuri_Matsumura", "notes": "Fashion model and actress."},
    {"qid": "Q11581294", "name": "Tsubasa Masuwaka", "dob": "1985-10-13", "occ": "fashion model", "ig": "tsubasamasuwaka1013", "tt": "tsubasamasuwaka1013", "wiki": "https://en.wikipedia.org/wiki/Tsubasa_Masuwaka", "notes": "Fashion model, product designer, and entrepreneur."},
    {"qid": "Q11583120", "name": "Naomi Majima", "dob": "1998-03-17", "occ": "fashion model", "ig": "naomi_majima", "tt": "naomi_majima", "notes": "Fashion model and television talent."},
    {"qid": "Q11473103", "name": "Natsumi Okamoto", "dob": "1998-07-01", "occ": "fashion model", "ig": "okamoto_natsumi", "tt": "natsumiokamoto_mg", "wiki": "https://en.wikipedia.org/wiki/Natsumi_Okamoto", "notes": "Fashion model and actress."},
    {"qid": "Q11491098", "name": "Yūmi Shida", "dob": "1997-02-11", "occ": "fashion model", "ig": "yuumi_shida", "tt": "yuumi_shida", "wiki": "https://en.wikipedia.org/wiki/Yumi_Shida", "notes": "Fashion model and actress."},
    {"qid": "Q21198517", "name": "Dakota Rose", "dob": "1986-09-19", "occ": "fashion model", "ig": "koti.rose", "tt": "dakotakoti", "wiki": "https://en.wikipedia.org/wiki/Dakota_Rose", "notes": "Fashion model and beauty creator."},
    {"qid": "Q22127071", "name": "Haruka Iwasaki", "dob": "2003-04-26", "occ": "fashion model", "ig": "haru_san.03", "tt": "h.i0426", "notes": "Fashion model and actress."},
    {"qid": "Q22128771", "name": "Hitoka Sakai", "dob": "2001-07-25", "occ": "fashion model", "ig": "hitoka_sakai_official", "tt": "hitoka_sakai_official", "notes": "Fashion model and television personality."},
    {"qid": "Q11622669", "name": "Sachi Fujii", "dob": "1997-03-06", "occ": "fashion model", "ig": "sachi_fujii_official", "tt": "sachi_fujii_official", "wiki": "https://en.wikipedia.org/wiki/Sachi_Fujii", "notes": "Fashion model and fitness enthusiast."},
    {"qid": "Q11624970", "name": "Mio Kudō", "dob": "1999-10-08", "occ": "fashion model", "ig": "mmio_kudo", "tt": "mmio_kudo30", "wiki": "https://en.wikipedia.org/wiki/Mio_Kudo", "notes": "Fashion model and actress."},
    {"qid": "Q11632580", "name": "Maria Tani", "dob": "1995-07-28", "occ": "fashion model", "ig": "mariaaaa728", "tt": "mariaaaa728", "wiki": "https://en.wikipedia.org/wiki/Maria_Tani", "notes": "Fashion model and television personality."},
    {"qid": "Q1051728", "name": "Rina Katsuta", "dob": "1998-04-06", "occ": "fashion model", "ig": "rinakatsuta", "tt": "rinakatsuta_", "wiki": "https://en.wikipedia.org/wiki/Rina_Katsuta", "notes": "Fashion model and apparel designer."},

    # --- Beach Volleyball & NCAA / International Stars ---
    {"qid": "Q4578", "name": "Laura Ludwig", "dob": "1986-01-13", "occ": "beach volleyball player", "ig": "lauraludwig86", "wiki": "https://en.wikipedia.org/wiki/Laura_Ludwig", "notes": "German Beach Volleyball Olympic Gold Medalist, World Champion, and 4x European Champion."},
    {"qid": "Q99534664", "name": "Devon Newberry", "dob": "2000-01-01", "occ": "beach volleyball player", "ig": "devnewberry", "notes": "UCLA Bruins 2x NCAA Beach Volleyball National Champion and All-American."},
    {"qid": "Q110411248", "name": "Aline Chamereau", "dob": "1996-03-06", "occ": "beach volleyball player", "ig": "aline__cham", "tt": "alinechamereau", "wiki": "https://en.wikipedia.org/wiki/Aline_Chamereau", "notes": "France Olympic Beach Volleyball athlete."},
    {"qid": "Q139036727", "name": "Michaela Páneková", "dob": "2003-10-25", "occ": "beach volleyball player", "ig": "_panekova.michaela_", "tt": "michaela.panekova", "notes": "Slovakia Beach Volleyball National Team athlete."},
    {"qid": "Q98271305", "name": "Claudia Scampoli", "dob": "2000-04-05", "occ": "beach volleyball player", "ig": "claudiascampoli", "notes": "Italy Beach Volleyball National Team athlete and World Tour medalist."},
    {"qid": "Q99510689", "name": "Frida Berntsen", "dob": "2001-10-16", "occ": "beach volleyball player", "ig": "frida_berntsen", "notes": "Norway Beach Volleyball National Team athlete."},
    {"qid": "Q99387328", "name": "Alexia Căruțașu", "dob": "2003-06-10", "occ": "volleyball player", "ig": "alexiaioanacarutasu", "wiki": "https://en.wikipedia.org/wiki/Alexia_C%C4%83ru%C8%9Ba%C8%99u", "notes": "Galatasaray / VakifBank Sultanlar Ligi opposite and Turkey / Romania National Team star."},
    {"qid": "Q98098539", "name": "Blake Mohler", "dob": "1996-12-30", "occ": "volleyball player", "ig": "blakemohler", "tt": "blakemohler1", "notes": "Purdue Boilermakers NCAA All-American middle blocker, VfB Suhl Bundesliga star, and LOVB athlete."},
    {"qid": "Q98923948", "name": "Marijeta Runjić", "dob": "1996-04-11", "occ": "volleyball player", "ig": "marijetarunjic", "notes": "UTSA Roadrunners NCAA All-American outside hitter and Croatia National Team athlete."},
    {"qid": "Q98704582", "name": "Emily Konstantellou", "dob": "1997-05-27", "occ": "volleyball player", "ig": "emily.kon", "notes": "Olympiacos / Panathinaikos middle blocker and Greece National Team athlete."},
    {"qid": "Q98520060", "name": "Ioanna Kasdovasili", "dob": "1997-05-13", "occ": "volleyball player", "ig": "iwannakas", "notes": "Panathinaikos middle blocker and Greece National Team athlete."},
    {"qid": "Q98704581", "name": "Panagiota Dioti", "dob": "1992-11-13", "occ": "volleyball player", "ig": "dioti_giota", "notes": "Panathinaikos outside hitter and Greece National Team athlete."},
    {"qid": "Q99519745", "name": "Konstantina Passia", "dob": "1993-10-30", "occ": "volleyball player", "ig": "konstantina_pass", "notes": "Greece National Team setter and Markopoulo athlete."},
    {"qid": "Q99519790", "name": "Eirini Kelesidou", "dob": "1991-05-16", "occ": "volleyball player", "ig": "eirini_kelekele", "notes": "Olympiacos / PAOK Thessaloniki libero and Greece National Team athlete."},
    {"qid": "Q83546604", "name": "Kathryn Plummer", "dob": "1998-10-16", "occ": "volleyball player", "ig": "kathrynplummer", "wiki": "https://en.wikipedia.org/wiki/Kathryn_Plummer", "notes": "Stanford 3x NCAA Champion, Imoco Conegliano / Eczacibasi outside hitter, and USA Olympic Silver Medalist."},
    {"qid": "Q88927741", "name": "Dana Rettke", "dob": "1999-01-20", "occ": "volleyball player", "ig": "dana_rettke", "wiki": "https://en.wikipedia.org/wiki/Dana_Rettke", "notes": "Wisconsin Badgers NCAA Champion, AVCA National Player of the Year, Vero Volley Milano / Eczacibasi, and USA Olympic Silver Medalist."},
    {"qid": "Q89920715", "name": "Jenna Gray", "dob": "1998-02-28", "occ": "volleyball player", "ig": "jmoneyyy222", "wiki": "https://en.wikipedia.org/wiki/Jenna_Gray", "notes": "Stanford 3x NCAA Champion setter, Dresdner SC / Gerdau Minas star, and LOVB athlete."},
    {"qid": "Q96079670", "name": "Morgan Hentz", "dob": "1998-07-27", "occ": "volleyball player", "ig": "morganhentz", "wiki": "https://en.wikipedia.org/wiki/Morgan_Hentz", "notes": "Stanford 3x NCAA Champion libero, LOVB Atlanta athlete, and USA National Team star."},
    {"qid": "Q96209152", "name": "Madeleine Gates", "dob": "1998-10-30", "occ": "volleyball player", "ig": "madeleine.gates", "wiki": "https://en.wikipedia.org/wiki/Madeleine_Gates", "notes": "Stanford NCAA Champion / UCLA All-American middle blocker, Dresdner SC star, and LOVB athlete."},
    {"qid": "Q96737806", "name": "Júlia Bergmann", "dob": "2001-02-21", "occ": "volleyball player", "ig": "juliabergmann6", "wiki": "https://en.wikipedia.org/wiki/J%C3%BAlia_Bergmann", "notes": "Georgia Tech NCAA All-American, THY Sultanlar Ligi outside hitter, and Brazil Olympic Bronze Medalist."},
    {"qid": "Q96776156", "name": "Tainara Santos", "dob": "2000-03-09", "occ": "volleyball player", "ig": "tainaras10", "wiki": "https://en.wikipedia.org/wiki/Tainara_Santos", "notes": "Shanghai / Dentil Praia Clube opposite and Brazil Olympic Bronze Medalist."},
    {"qid": "Q96902355", "name": "Derya Cebecioğlu", "dob": "2000-10-24", "occ": "volleyball player", "ig": "deryacebeciogluu", "wiki": "https://en.wikipedia.org/wiki/Derya_Cebecio%C4%9Flu", "notes": "VakifBank Istanbul / Kurobe AquaFairies outside hitter and Turkey National Team star."},
    {"qid": "Q97189709", "name": "Yasemin Güveli", "dob": "1999-01-05", "occ": "volleyball player", "ig": "yaseminguvelii", "wiki": "https://en.wikipedia.org/wiki/Yasemin_G%C3%BCveli", "notes": "Eczacibasi Dynavit / Galatasaray middle blocker and Turkey National Team athlete."},
    {"qid": "Q85871654", "name": "Esmée Böbner", "dob": "1999-11-03", "occ": "beach volleyball player", "ig": "esmeeboebner", "wiki": "https://en.wikipedia.org/wiki/Esm%C3%A9e_B%C3%B6bner", "notes": "Swiss Olympic Beach Volleyball athlete and European Tour champion."},
    {"qid": "Q85879035", "name": "Zoé Vergé-Dépré", "dob": "1998-02-23", "occ": "beach volleyball player", "ig": "zoe.vergedepre", "wiki": "https://en.wikipedia.org/wiki/Zo%C3%A9_Verg%C3%A9-D%C3%A9pr%C3%A9", "notes": "Swiss Olympic Beach Volleyball athlete and World Tour medalist."},
    {"qid": "Q807859", "name": "Barbora Hermannová", "dob": "1990-11-07", "occ": "beach volleyball player", "ig": "bara.hermannova", "wiki": "https://en.wikipedia.org/wiki/Barbora_Hermannov%C3%A1", "notes": "Czech Republic 2x Olympic Beach Volleyball athlete and European Champion."},
    {"qid": "Q9142328", "name": "Agnieszka Korneluk", "dob": "1994-10-17", "occ": "volleyball player", "ig": "agaa_kakaa", "wiki": "https://en.wikipedia.org/wiki/Agnieszka_Korneluk", "notes": "DevelopRes Rzeszow / Chemik Police middle blocker and Poland National Team Olympian."},
    {"qid": "Q9179115", "name": "Brayelin Martínez", "dob": "1996-09-11", "occ": "volleyball player", "ig": "_bem20", "wiki": "https://en.wikipedia.org/wiki/Brayelin_Mart%C3%ADnez", "notes": "Savino Del Bene Scandicci / Dentil Praia Clube outside hitter and Dominican Republic Olympian."},
    {"qid": "Q9356873", "name": "Teodora Pušić", "dob": "1994-03-12", "occ": "volleyball player", "ig": "teodora.pusic", "wiki": "https://en.wikipedia.org/wiki/Teodora_Pu%C5%A1i%C4%87", "notes": "Numia Vero Volley Milano / Allianz MTV Stuttgart libero and Serbia 2x World Champion."},
    {"qid": "Q93753726", "name": "Eline Timmerman", "dob": "1998-12-30", "occ": "volleyball player", "ig": "elinetimmerman", "wiki": "https://en.wikipedia.org/wiki/Eline_Timmerman", "notes": "Galatasaray / Allianz MTV Stuttgart middle blocker and Netherlands National Team Olympian."},
    {"qid": "Q946914", "name": "Valentina Diouf", "dob": "1993-01-10", "occ": "volleyball player", "ig": "durbansmile", "wiki": "https://en.wikipedia.org/wiki/Valentina_Diouf", "notes": "Numia Vero Volley Milano / Busto Arsizio opposite and Italy National Team star."},
    {"qid": "Q967009", "name": "Monica De Gennaro", "dob": "1987-01-08", "occ": "volleyball player", "ig": "mokidegennaroofficial", "wiki": "https://en.wikipedia.org/wiki/Monica_De_Gennaro", "notes": "Imoco Conegliano Serie A1 libero, Italy Olympic Gold Medalist & MVP, and 2x World Championship Best Libero."},
    {"qid": "Q96097580", "name": "Monique Strubbe", "dob": "2001-07-05", "occ": "volleyball player", "ig": "moniquestrubbe", "notes": "Allianz MTV Stuttgart / Dresdner SC middle blocker and Germany National Team star."},
    {"qid": "Q96097900", "name": "Sarah Straube", "dob": "2002-04-26", "occ": "volleyball player", "ig": "sarah_straube", "notes": "Dresdner SC Bundesliga setter and Germany National Team athlete."},
    {"qid": "Q96089940", "name": "Meghan Barthel", "dob": "2000-03-23", "occ": "volleyball player", "ig": "meghanbarthel", "notes": "Dresdner SC Bundesliga setter."},
    {"qid": "Q93874125", "name": "Patricia Nestler", "dob": "2001-05-17", "occ": "volleyball player", "ig": "patricia_nestler", "notes": "Dresdner SC / SSC Palmberg Schwerin Bundesliga libero."},
    {"qid": "Q96474219", "name": "Lina-Marie Lieb", "dob": "2001-07-30", "occ": "volleyball player", "ig": "_l1nalieb_", "notes": "Schwarz-Weiss Erfurt Bundesliga outside hitter."},
    {"qid": "Q96337387", "name": "Kelsey Veltman", "dob": "1996-04-02", "occ": "volleyball player", "ig": "kelsey_veltman", "notes": "Western Mustangs CIS Champion, Schwarz-Weiss Erfurt middle blocker, and Canada National Team athlete."},
    {"qid": "Q97105403", "name": "Claudia Provaroni", "dob": "1998-05-14", "occ": "volleyball player", "ig": "claudiaprovaroni2.0", "notes": "Trentino Rosa / Bartoccini Fortinfissi Perugia Serie A1 libero."}
]

print(f"Total session 25 candidates: {len(SESSION25_CANDIDATES)}")
