import json,re
from pathlib import Path
new=json.load(open('data/research/s29_raw/model_gt2_checked.json'))
by={r['qid']:r for r in new}
# verdict table: qid -> (verdict, category_or_flags, note, dob_override, ig_override, tt_override)
V={}
def P(q,cat,note,dob=None,ig=None,tt=None): V[q]=('PROMOTE',cat,note,dob,ig,tt)
def R(q,flags,note,ig=None,tt=None): V[q]=('REVIEW',flags,note,None,ig,tt)
def X(q,note): V[q]=('REJECT','excluded',note,None,None,None)
SA='no modeling/creator activity documented in lead; adult (DOB matches Wikidata)'
# --- batch 0
R('Q134408344','AGE_PARTIAL','ID pageant titleholder (Puteri Indonesia Pariwisata 2025, Miss Cosmo 2025 Top 21); en-wiki lead and infobox carry no birth date (birth_date empty); Wikidata 2003-01-15 unconfirmed on page')
P('Q134416154','Modeling/TV','EN television personality, presenter, model and campaigner (Married at First Sight 2023); DOB matches Wikidata')
R('Q134599275','DOB_CONFLICT','ZA actress and influencer (The River); en-wiki lead DOB 8 February 1998 vs Wikidata 1998-02-07 - day-level conflict, no value chosen (both adult)')
P('Q134649377','Beauty pageant/modeling','FR-BG model and pageant titleholder, Miss Universe Bulgaria 2025; DOB matches Wikidata')
P('Q13477906','Beauty pageant/modeling/TV','US TV host, model and pageant titleholder, Miss USA 2013; DOB matches Wikidata')
P('Q135069753','Beauty pageant/modeling','UA model and entrepreneur, Miss Universe Ukraine 2025; DOB matches Wikidata')
P('Q135106203','Beauty pageant/modeling','BR model and pageant titleholder, Miss Supranational 2025; DOB matches Wikidata')
P('Q135259158','Beauty pageant/modeling','ID model, marketing specialist and pageant titleholder, Miss Indonesia 2025; DOB matches Wikidata; age 23')
R('Q135474865','WIKI_REDIRECT+AGE_PARTIAL','US YouTuber/creator (Wikidata label Suzy Berhow); the en-wiki title redirects to the article of Arin Hanson (Game Grumps co-founder), so no article of her own confirms the Wikidata DOB 1989-07-03; creator activity to be confirmed on her own channels')
P('Q13551995','Modeling/acting','ID actress and model; DOB matches Wikidata')
R('Q13560257','scope-ambiguous','IL actress (Underemployed, Gang Related, Prison Break); '+SA)
R('Q13560262','scope-ambiguous','US television personality, singer, podcast host and actress (Vanderpump Rules); '+SA)
R('Q13560265','AGE_PARTIAL+scope-ambiguous','US actress (Superstore, Shameless); en-wiki lead and infobox carry no birth date; Wikidata 1989-12-15 unconfirmed on page; no modeling/creator activity in lead')
R('Q13560423','scope-ambiguous','US singer and actress (Liv and Maddie, Descendants); '+SA)
P('Q13560508','Modeling/acting','MX actress and former fashion model (Nuestra Belleza Latina 2013 finalist); DOB matches Wikidata')
P('Q13561648','Modeling/acting','US fashion model and actress; DOB matches Wikidata')
P('Q13561651','Modeling/wrestling','US professional wrestler, model, singer and ring announcer (WWE); DOB matches Wikidata')
R('Q13561664','DOB_CONFLICT+GENDER_EVIDENCE_REVIEW','US plus-size model (H&M 2013 beachwear campaign); en-wiki lead DOB November 2, 1988 vs Wikidata 1989-06-13 - conflict, no value chosen (both adult); en-wiki lead uses they/them pronouns while Wikidata records female - gender record needs manual confirmation from a first-party source')
P('Q13571519','Beauty pageant/modeling','PY model and pageant titleholder, Nuestra Belleza Paraguay 2013 / Miss Universe 2013; DOB matches Wikidata')
P('Q136265985','Beauty pageant/modeling','MX model and pageant titleholder, Miss Universe 2025; DOB matches Wikidata')
# --- batch 1
P('Q136373848','Modeling/Creator/TV','US model, influencer and television personality (Love Island USA season 7 runner-up); DOB matches Wikidata')
P('Q13643654','Modeling/acting','US model and actress; DOB matches Wikidata')
R('Q136455412','DOB_CONFLICT','IL pageant titleholder, Miss Israel 2025 / Miss Universe 2025; en-wiki lead DOB November 13, 1998 vs Wikidata 1999-01-01 - year-level conflict (not a simple precision issue), no value chosen (both adult)')
P('Q136672990','Beauty pageant','ZA pageant titleholder, Miss Earth South Africa 2021, Miss South Africa 2024 1st runner-up; DOB matches Wikidata')
P('Q136708336','Beauty pageant','CZ pageant titleholder, Miss Earth 2025; DOB matches Wikidata; age 22')
P('Q136758548','Beauty pageant/modeling/music','CL model, singer and pageant titleholder, Miss World Chile 2025; DOB matches Wikidata')
R('Q1367697','DOB_CONFLICT','CA fashion model; en-wiki lead DOB July 25, 1988 while Wikidata carries two full dates (1987-05-27 and 1988-07-25) - unresolved source conflict, no value chosen (both adult)')
P('Q136788710','Beauty pageant','ZW pageant titleholder and film producer, Miss Cosmo Zimbabwe 2026; DOB matches Wikidata')
R('Q137101812','AGE_PARTIAL','CN pageant titleholder, Miss Universe China 2025 / Miss Universe Asia 2025; en-wiki lead and infobox carry no birth date (birth_date empty); Wikidata 2005-01-27 unconfirmed on page')
R('Q137115597','AGE_PARTIAL','EN businesswoman, model and pageant titleholder (Miss Cosmo 2024, Miss World 2025); en-wiki gives birth year only (born 2000, infobox birth_date 2000); Wikidata 2000-01-01 is year-precision; full DOB not documented')
R('Q1371627','scope-ambiguous','DE actress (Spring, The 100, The Walking Dead); infobox DOB 1 December 1988 matches Wikidata; no modeling/creator activity in lead')
R('Q137187747','DOB_CONFLICT','PH-IR model, actress, singer and pageant titleholder (Face of Beauty International 2025); en-wiki lead DOB June 4, 2003 vs Wikidata 1998-06-04 - year-level conflict, no value chosen (both adult)')
X('Q137459163','Not an individual person: the en-wiki article and the princesskilltown / PrincessKilltown accounts belong to the Thai musical duo Princess Kill (twin sisters); the Wikidata item is mis-typed as human. The elder twin Nutnacha Krusagayavong (Q137513862) is assessed separately')
P('Q1375057','Modeling/TV','US model, socialite and media personality; DOB matches Wikidata')
P('Q137513862','Modeling/music/acting','TH singer-songwriter, rapper, model, actress and voice actress (member of duo Princess Kill); DOB matches Wikidata; Wikidata TikTok PrincessKilltown is the duo account and is not recorded for her',tt='')
P('Q137647653','Modeling','IN fashion model (opened the Chanel Metiers d Art 2026 show); DOB matches Wikidata')
P('Q137793805','Beauty pageant/modeling','IS model and pageant titleholder, Miss Universe Iceland 2024, Miss Earth Air 2025; DOB matches Wikidata; age 20')
P('Q138034854','Beauty pageant','ID pageant titleholder, Puteri Indonesia 2026; DOB matches Wikidata; Wikidata TikTok rahajengsisters appears to be a joint sisters account and is not recorded',tt='')
R('Q138824','scope-ambiguous','MX singer and actress; '+SA)
P('Q140099','Modeling/entertainment','KR singer, actress, model, host and lyricist (T-ara); DOB matches Wikidata')
# --- batch 2
P('Q14316484','Modeling/acting','MY actress and model; DOB matches Wikidata')
P('Q14467340','Beauty pageant/modeling/acting','DO actress, singer, model and pageant titleholder (Miss Dominican Republic 2013, Miss World 2016 1st runner-up); DOB matches Wikidata')
R('Q14538236','scope-ambiguous','DE singer and actress; '+SA)
P('Q14542188','Modeling/TV','BR model and TV presenter (Panico na TV); DOB matches Wikidata')
P('Q14548311','Modeling','EN fashion model (Victoria s Secret); DOB matches Wikidata')
P('Q14566589','Modeling/acting','JP actress and fashion model (Horipro); DOB matches Wikidata')
P('Q14776563','Modeling','DE-NG fashion model, winner of Germany s Next Topmodel cycle 8; DOB matches Wikidata')
P('Q14864127','Modeling/acting','PK actress and model; lead undated; en-wiki infobox birth_date 7 Feb 1986 matches Wikidata')
P('Q14864312','Beauty pageant/modeling','ID dancer, model and pageant titleholder, Puteri Indonesia Pariwisata 2013 / Miss Supranational 2013 3rd runner-up; DOB matches Wikidata')
R('Q14864898','scope-ambiguous','PK film and TV actress; '+SA)
R('Q14865082','DOB_CONFLICT','PK actress and model; en-wiki lead DOB 8 September 1972 vs Wikidata 1991-05-15 - major conflict, no value chosen (both adult)')
R('Q14880277','WIKI_REDIRECT+AGE_PARTIAL+scope-ambiguous','JP idol singer (former Angerme member); the en-wiki title redirects to the group article Angerme, so no article of her own confirms the Wikidata DOB 2001-05-28; no modeling/creator activity documented')
P('Q14915104','Beauty pageant','LB pageant titleholder and interior designer, Miss Lebanon 2013; en-wiki DOB 10 July 1991 matches the full Wikidata value 1991-07-10; Wikidata also carries a duplicate 1991-01-01 year-precision statement (noted, not a conflict)',dob='1991-07-10')
P('Q14915318','Modeling/entertainment','JP actress, model and variety tarento; DOB matches Wikidata')
P('Q14917363','Beauty pageant/TV','US public speaker, advocate and beauty queen, Miss America 2014, TV host; DOB matches Wikidata')
P('Q14917756','Modeling/acting','CL actress and model; DOB matches Wikidata')
R('Q14949578','DOB_CONFLICT','AR fashion model and artist; en-wiki lead DOB 12 October 1990 vs Wikidata 1991-10-12 - year-level conflict, no value chosen (both adult)')
R('Q14955035','scope-ambiguous','RS singer (Zvezde Granda); '+SA)
P('Q14955068','Creator/music','US singer-songwriter and actress who debuted on YouTube in 2009 (creator origin documented in lead); DOB matches Wikidata')
P('Q14956451','Modeling/acting','PH actress, commercial model and entrepreneur; DOB matches Wikidata')
# --- batch 3
R('Q15055683','scope-ambiguous','IN film actress; '+SA)
P('Q15059451','Modeling/acting','MY actress and commercial model; DOB matches Wikidata')
R('Q15059490','scope-ambiguous','US singer-songwriter and television personality; '+SA)
R('Q15061909','AGE_PARTIAL+scope-ambiguous','NP singer (Nepal Idol judge; short description: singer and model); en-wiki page has no birth date (no infobox); Wikidata 1986-07-18 unconfirmed on page; modeling only in the short description, not in the lead')
R('Q15069886','scope-ambiguous','US actress and singer; '+SA)
R('Q15075435','scope-ambiguous','RU journalist with episodic film roles; '+SA)
P('Q15079800','Modeling/acting/music','FR actress, singer and fashion model; DOB matches Wikidata')
R('Q15095116','scope-ambiguous','VE telenovela actress; '+SA)
P('Q15102566','Modeling/acting/art','US actress, model, visual artist and entrepreneur; DOB matches Wikidata')
R('Q15106798','AGE_PARTIAL','US actress and model (American Horror Story; first woman with Down syndrome to walk NYFW 2015); en-wiki gives only born 1984 or 1985 (age-derived infobox); Wikidata 1985-02-05 unconfirmed on page')
R('Q15106925','AGE_PARTIAL','CR television actress and model; en-wiki page has no birth date (no infobox); Wikidata 1986-02-26 unconfirmed on page')
R('Q15107401','DOB_CONFLICT','BR television actress and model; en-wiki lead DOB 29 November 1989 vs Wikidata 1989-11-26 - day-level conflict, no value chosen (both adult)')
R('Q151118','scope-ambiguous','US actress, singer and dancer (The Vampire Diaries); '+SA)
R('Q15120693','DOB_CONFLICT','BR dancer, model and pageant titleholder, Miss Brazil 2013; en-wiki lead DOB March 18, 1993 vs Wikidata 1993-01-20 - conflict, no value chosen (both adult)')
P('Q15123123','Beauty pageant/modeling/TV','IT beauty queen (Miss Italia 2013), actress, TV presenter and model; DOB matches Wikidata')
P('Q15148556','Beauty pageant/modeling','CO model, business administrator and pageant titleholder, Miss Universe 2014; DOB matches Wikidata')
R('Q151892','scope-ambiguous','US singer, songwriter and actress; '+SA)
P('Q15214868','Modeling','US fashion model, winner of America s Next Top Model cycle 20; DOB matches Wikidata')
P('Q1528090','Modeling/acting','AR actress and model; DOB matches Wikidata')
R('Q15285465','scope-ambiguous','KR actress; '+SA)
# --- batch 4
P('Q15287910','Modeling','DK model; DOB matches Wikidata')
P('Q15287955','Beauty pageant/modeling','FR model and pageant titleholder, Miss France 2014; DOB matches Wikidata')
P('Q15290780','Modeling','CZ model, Elite Model Look International 2013 winner; lead undated; en-wiki infobox birth_date 12 Oct 1997 matches Wikidata')
R('Q15296099','scope-ambiguous','BD singer; '+SA)
R('Q15300228','DOB_CONFLICT','BD actress, model and producer; en-wiki lead DOB 20 February 1982 vs Wikidata 1989-02-20 - year-level conflict, no value chosen (both adult)')
R('Q15304882','scope-ambiguous','TR actress and former dancer; '+SA)
P('Q15391053','Beauty pageant/modeling/acting','PH fashion and commercial model, actress and beauty queen, Miss Supranational 2013; DOB matches Wikidata')
R('Q15410607','scope-ambiguous','US actress (The Bold and the Beautiful); '+SA)
R('Q1541103','scope-ambiguous','US actress; '+SA)
P('Q15515416','Modeling/acting','MY actress and model; DOB matches Wikidata')
P('Q15554616','Modeling/acting','BE actress, model and author; DOB matches Wikidata')
P('Q15608669','Beauty pageant/modeling/TV','VE actress, TV host, model and pageant titleholder (Miss Venezuela 2013); DOB matches Wikidata')
P('Q15618487','Beauty pageant/modeling','NL-IT model and pageant titleholder, Miss Universo Italia 2013; DOB matches Wikidata')
P('Q15626821','Modeling/acting','BD model and actress; en-wiki DOB 30 Mar 1988 preferred over Wikidata 1988-01-01 (year-precision)',dob='1988-03-30')
P('Q15631446','Modeling','KE-GB model (Prada campaign 2013); DOB matches Wikidata')
R('Q15634981','WIKI_REDIRECT+AGE_PARTIAL','UY pageant titleholder per Wikidata (label Johana Riva); the en-wiki title redirects to the pageant article Miss Uruguay, so no article of her own confirms the Wikidata DOB 1990-11-23')
R('Q1563876','scope-ambiguous','CO television actress and singer; '+SA)
P('Q15639740','Modeling/acting','AR actress and model; DOB matches Wikidata')
R('Q15645408','scope-ambiguous','IN film actress; '+SA)
R('Q1564850','scope-ambiguous','AU actress; '+SA)
# --- batch 5
P('Q15677990','Modeling/acting/music','ID actress, model and singer; DOB matches Wikidata')
P('Q15690129','Beauty pageant/modeling/acting','ID actress, model and pageant titleholder, Puteri Indonesia 2014 / Miss Universe 2014 Top 15; DOB matches Wikidata')
R('Q15690325','DOB_CONFLICT','ID model and pageant titleholder, Puteri Indonesia Lingkungan 2014; en-wiki lead DOB 23 September 1995 vs Wikidata 1995-12-23 - month-level conflict, no value chosen (both adult)')
R('Q15696586','scope-ambiguous','PH-US actress; '+SA)
P('Q15698830','Modeling/acting','JP actress, model and gravure idol (Horipro); DOB matches Wikidata')
P('Q15712311','Modeling/music/TV','IL fashion model, singer and television personality; DOB matches Wikidata')
R('Q15713168','scope-ambiguous','BD film actress; '+SA)
P('Q15714672','Modeling/acting/music','AR actress, model and singer (Soy Luna); DOB matches Wikidata')
P('Q15715461','Modeling/acting/music','TW actress, model and singer; DOB matches Wikidata')
R('Q15716791','DOB_CONFLICT','US actress and model (General Hospital); en-wiki lead DOB August 28, 1982 vs Wikidata 1985-08-01 - year-level conflict, no value chosen (both adult)')
R('Q15739824','scope-ambiguous','US professional wrestling manager, retired wrestler and actress (WWE, ring name Lana); '+SA)
P('Q15743863','Modeling','RU-US alternative model and burlesque performer; DOB matches Wikidata')
P('Q15779965','Beauty pageant/modeling','BD model and lawyer, Miss Bangladesh 2007; lead undated; en-wiki infobox birth_date 14 Oct 1991 matches Wikidata')
P('Q15794518','Modeling/acting','EN actress and model; DOB matches Wikidata')
P('Q1579932','Modeling/TV/acting','BR actress, writer and TV host whose lead documents her modeling career with the Ford Models agency in Sao Paulo; DOB matches Wikidata')
R('Q1580624','scope-ambiguous','AU actress; '+SA)
R('Q1582005','scope-ambiguous','EN actress; '+SA)
R('Q15829736','AGE_PARTIAL','US runway and editorial fashion model, actress and photographer; en-wiki lead and infobox carry no birth date (birth_date empty); Wikidata 1987-12-21 unconfirmed on page')
R('Q15838455','AGE_PARTIAL','SE model and actress; en-wiki gives birth year only (born 1990; infobox birth year and age); Wikidata 1990-05-11 unconfirmed on page')
R('Q158450','scope-ambiguous','IN former film actress; '+SA)
# --- batch 6
P('Q15846080','Modeling/sports','ES retired rhythmic gymnast, cheerleader and model; DOB matches Wikidata')
R('Q15898948','DOB_CONFLICT','BD actress and model; en-wiki infobox birth_date 27 December 1988 vs Wikidata 1988-09-04 - conflict, no value chosen (both adult); lead undated')
R('Q159178','scope-ambiguous','IN film actress; '+SA)
R('Q15921914','AGE_PARTIAL+scope-ambiguous','SG actress and singer; en-wiki lead and infobox carry no birth date; Wikidata 1986-03-12 unconfirmed on page; no modeling/creator activity in lead')
P('Q15923684','Modeling/music/acting','HK singer, actress and model (advertising campaigns for McDonald s, Olympus, K-Swiss); lead undated; en-wiki infobox birth_date 27 Dec 1993 matches Wikidata')
R('Q15934116','scope-ambiguous','KR singer and dancer (Red Velvet); '+SA)
P('Q15934767','Modeling/wrestling','US professional wrestler, valet and model (WOW); DOB matches Wikidata')
R('Q15944159','scope-ambiguous','JP singer and dancer (Babymetal); no modeling/creator activity in lead; the Wikidata Instagram babymetal_official is the band account, not a personal profile, and is not recorded; adult (DOB matches Wikidata)',ig='')
R('Q15944569','scope-ambiguous','JP actress and pop singer; '+SA)
P('Q15944829','Modeling/acting','US actress and model (Banshee, Power Book IV: Force); DOB matches Wikidata')
R('Q15973005','AGE_PARTIAL','US model, designer and television personality (Breaking Amish); en-wiki lead and infobox carry no birth date (birth_date empty); Wikidata 1991-01-01 is year-precision only')
R('Q15983216','AGE_PARTIAL','PK model and singer (Lux Style Awards nominee); en-wiki lead and infobox carry no birth date (birth_date empty); Wikidata 1993-07-30 unconfirmed on page')
P('Q15983355','Modeling/acting','PK actress and model; lead gives born 1990; en-wiki infobox birth_date 11 Oct 1990 matches Wikidata')
P('Q15989682','Beauty pageant','ZA beauty queen, Miss South Africa 2014 and Miss World 2014; DOB matches Wikidata')
P('Q15992427','Modeling/TV','FR television presenter and former model; DOB matches Wikidata')
P('Q16049782','Modeling/acting','IR model and former actress; DOB matches Wikidata')
R('Q16057974','DOB_CONFLICT','MY actress and model (Sabah); en-wiki lead DOB 19 March 1992 vs Wikidata 1992-03-12 - day-level conflict, no value chosen (both adult)')
P('Q16058172','Beauty pageant/modeling/acting','IN actress, model and pageant titleholder, Miss India International 2021 / Miss International 2022; DOB matches Wikidata')
P('Q16065114','Modeling/music/creator','Kurdish singer, dancer, choreographer, actress and model who rose to fame through cover videos on Myspace and YouTube; DOB matches Wikidata')
missing=[r['qid'] for r in new if r['qid'] not in V]
extra=[q for q in V if q not in by]
print('missing',missing,'extra',extra)
lines=[];buckets=[]
def title_name(t): return re.sub(r'\s*\(.*?\)\s*$','',t)
for r in new:
    q=r['qid']; verdict,cat,note,dob,igo,tto=V[q]
    name=title_name(r['title'])
    ex=r['extract'].replace('\n',' ').replace('|','/')
    if ex.startswith('[REDIRECT'): quote=ex[:200]
    else: quote=ex if len(ex)<=230 else ex[:230].rsplit(' ',1)[0]+'...'
    d=dob or r['dob']
    ev=f'en-wiki lead: "{quote}" - {note}'
    if verdict=='REJECT': ev=note
    assert '|' not in ev, q
    lines.append(f"{q}|{name}|{d}|{verdict}|{cat}|{ev}|{r['wiki']}")
    buckets.append(dict(qid=q,name=name,dob=d,ig=(r['ig'] if igo is None else igo),tt=(r['tt'] if tto is None else tto),wiki=r['wiki'],file='model_gt2_chunk*.txt'))
Path('data/research/verification_s29_log.tsv').write_text('\n'.join(lines)+'\n')
json.dump({'model':buckets},open('data/research/s29_verify_buckets.json','w'),indent=1,ensure_ascii=False)
from collections import Counter
print(Counter(v[0] for v in V.values()))
print(Counter(v[1] for v in V.values() if v[0]=='REVIEW'))
